<?php


putenv('DISPLAY_ERRORS_DETAILS=' . true);

putenv('GERENCIADORDELOJAS_MYSQL_HOST=');
putenv('GERENCIADORDELOJAS_MYSQL_DBNAME=');
putenv('GERENCIADORDELOJAS_MYSQL_USER=');
putenv('GERENCIADORDELOJAS_MYSQL_PASSWORD=');
putenv('GERENCIADORDELOJAS_MYSQL_PORT=localhsot=3306');